apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nginx-deployment
  namespace: chisel-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-nginx
  template:
    metadata:
      labels:
        app: api-nginx
    spec:
      serviceAccountName: chisel-register-sa
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: api
          image: lukaszbielinski/chisel-register-api
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-data
              mountPath: /data
          ports:
            - containerPort: 8080
          env:
            # addres of chisel api
            - name: CHISEL_API_SERVER
              value: http://192.168.1.172
              # address where on control plane are exposed reverse tunnels
            - name: CHISEL_TUNNEL_DOMAIN
              value: https://chisel-tunnel.lan
              # domain where edges are registering
            - name: CHISEL_REGISTER_DOMAIN
              value: https://chisel-register.lan
              # domain where chisel clients are connecting
            - name: CHISEL_SERVER_DOMAIN
              value: https://chisel-server.lan
            - name: NAMESPACE
              value: chisel-server
              # chisel tunnel host in ingress, needed for certificate
            - name: CHISEL_TUNNEL_HOST
              value: chisel-tunnel
        - name: nginx
          image: nginx
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: 80
---
## list of users/passwords for api server
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-users
  namespace: chisel-server
type: Opaque
stringData:
  user1: password1
  user2: password2
  user3: password3
  admin: admin

---
apiVersion: v1
kind: Service
metadata:
  name: api-nginx-service
  namespace: chisel-server
spec:
  selector:
    app: api-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: api

  type: LoadBalancer
---

