---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chisel-register-sa
  namespace: chisel-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chisel-register-sa:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: chisel-register-sa
    namespace: chisel-server